# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rating', models.CharField(max_length=1, unique=True)),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(default='Stony Brook', max_length=64)),
                ('state', models.CharField(default='NY', max_length=2)),
                ('zip_code', models.CharField(default='11375', max_length=5)),
                ('description', models.TextField(blank=True, default='')),
                ('description_html', models.TextField(blank=True, default='', editable=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
