# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomshow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temprestaurant',
            options={'ordering': ['nameOfRestaurant']},
        ),
        migrations.RenameField(
            model_name='temprestaurant',
            old_name='name',
            new_name='nameOfRestaurant',
        ),
    ]
